using CarHorizontal.Domain.Entities.Timeline;

namespace CarHorizontal.Domain.Timeline.Rules;

/// <summary>
/// French private vehicles need a contrôle technique 4 years after first
/// registration, then every 2 years. We approximate via vehicle age.
/// </summary>
public sealed class AnnualTechnicalInspectionRule : IRule
{
    public const string RuleCode = "AnnualTechnicalInspection";
    public string Code => RuleCode;

    public bool Applies(RuleContext context)
    {
        var ageYears = context.Now.Year - context.Vehicle.Year;
        return ageYears >= 4;
    }

    public IEnumerable<TimelineEvent> Generate(RuleContext context)
    {
        var vehicle = context.Vehicle;

        var anchor = vehicle.PurchasedAt
            ?? new DateTime(vehicle.Year, 6, 1, 0, 0, 0, DateTimeKind.Utc);
        if (anchor.Kind != DateTimeKind.Utc)
        {
            anchor = DateTime.SpecifyKind(anchor, DateTimeKind.Utc);
        }

        var ageYears = context.Now.Year - vehicle.Year;
        DateTime nextInspection;

        if (ageYears < 4)
        {
            yield break;
        }

        if (ageYears < 6)
        {
            // first inspection at 4 years
            nextInspection = anchor.AddYears(4);
        }
        else
        {
            // recurring every 2 years
            var iteration = 0;
            DateTime candidate = anchor.AddYears(4);
            while (candidate < context.Now.AddDays(-15) && iteration < 30)
            {
                candidate = candidate.AddYears(2);
                iteration++;
            }
            nextInspection = candidate;
        }

        yield return new TimelineEvent
        {
            OrganizationId = vehicle.OrganizationId,
            VehicleId = vehicle.Id,
            CustomerId = vehicle.CustomerId,
            Kind = TimelineEventKind.TechnicalInspection,
            Title = "Contrôle technique à prévoir",
            Description = "Échéance estimée à partir de l'âge du véhicule.",
            DueAt = nextInspection,
            DueMileage = null,
            Status = TimelineEventStatus.Pending,
            Source = TimelineEventSource.AutoGenerated,
            GeneratedFromRule = RuleCode
        };
    }
}
