using CarHorizontal.Domain.Entities.Leasing;
using CarHorizontal.Domain.Entities.Timeline;

namespace CarHorizontal.Domain.Timeline.Rules;

/// <summary>
/// Règle d'accompagnement du leasing. Pour chaque contrat actif du véhicule :
/// 1. <b>Fin de contrat</b> : émet un événement quand l'échéance approche
///    (fenêtre ~4 mois), pour anticiper restitution ou renouvellement.
/// 2. <b>Risque de dépassement du plafond km</b> : projette le kilométrage à
///    l'échéance (estimation × jours restants) et alerte s'il dépasse le plafond
///    contractuel — y compris longtemps à l'avance, pour que le client ajuste.
/// Aucune donnée leasing = aucun événement (gating naturel par les données).
/// </summary>
public sealed class LeasingTimelineRule : IRule
{
    public const string RuleCode = "Leasing";

    /// <summary>Fenêtre d'anticipation de la fin de contrat.</summary>
    public const int LeaseEndLookaheadDays = 120;

    public string Code => RuleCode;

    public bool Applies(RuleContext context) =>
        context.LeasingContracts is { Count: > 0 } contracts
        && contracts.Any(c => c.Status == LeasingContractStatus.Active);

    public IEnumerable<TimelineEvent> Generate(RuleContext context)
    {
        if (context.LeasingContracts is null) yield break;

        var now = context.Now;

        foreach (var contract in context.LeasingContracts)
        {
            if (contract.Status != LeasingContractStatus.Active) continue;

            var end = ToUtc(contract.EndDate);

            // 1. Fin de contrat approchante (et pas trop ancienne).
            if (end >= now.AddMonths(-1) && end <= now.AddDays(LeaseEndLookaheadDays))
            {
                yield return new TimelineEvent
                {
                    OrganizationId = contract.OrganizationId,
                    VehicleId = contract.VehicleId,
                    CustomerId = contract.CustomerId,
                    Kind = TimelineEventKind.LeaseEnd,
                    Title = "Fin de contrat de leasing",
                    Description = $"Le contrat {contract.Lessor} arrive à échéance. " +
                                  "Anticiper avec le client la restitution ou un renouvellement.",
                    DueAt = end,
                    Status = TimelineEventStatus.Pending,
                    Source = TimelineEventSource.AutoGenerated,
                    GeneratedFromRule = RuleCode
                };
            }

            // 2. Risque de dépassement du plafond kilométrique.
            if (contract.MileageCapKm is int cap && context.CurrentMileageEstimate is { } estimate)
            {
                var daysToEnd = (end - estimate.AsOf).TotalDays;
                if (daysToEnd > 0)
                {
                    var projected = estimate.EstimatedKm + (int)Math.Round(estimate.DailyRate * daysToEnd);
                    if (projected > cap)
                    {
                        var overage = projected - cap;
                        yield return new TimelineEvent
                        {
                            OrganizationId = contract.OrganizationId,
                            VehicleId = contract.VehicleId,
                            CustomerId = contract.CustomerId,
                            Kind = TimelineEventKind.MileageCapRisk,
                            Title = "Risque de dépassement du plafond km (leasing)",
                            Description = $"Projection ~{projected} km à l'échéance pour un plafond de {cap} km " +
                                          $"(dépassement estimé ~{overage} km). Prévenir le client pour éviter des frais.",
                            // DueAt = échéance du contrat : repère stable pour la déduplication.
                            DueAt = end,
                            EstimatedKmRemaining = cap - estimate.EstimatedKm,
                            MileageConfidenceAtGeneration = estimate.Confidence.ToString(),
                            Status = TimelineEventStatus.Pending,
                            Source = TimelineEventSource.AutoGenerated,
                            GeneratedFromRule = RuleCode
                        };
                    }
                }
            }
        }
    }

    private static DateTime ToUtc(DateTime value)
        => value.Kind == DateTimeKind.Utc ? value : DateTime.SpecifyKind(value, DateTimeKind.Utc);
}
