using CarHorizontal.Domain.Entities.Timeline;

namespace CarHorizontal.Domain.Timeline.Rules;

/// <summary>
/// Generates a service event every 15 000 km, using the latest known
/// mileage to compute the next milestone.
/// </summary>
public sealed class MileageBasedServiceRule : IRule
{
    public const string RuleCode = "MileageBasedService";
    public const int Interval = 15_000;
    public string Code => RuleCode;

    public bool Applies(RuleContext context) => context.Vehicle.CurrentMileage >= 0;

    public IEnumerable<TimelineEvent> Generate(RuleContext context)
    {
        var vehicle = context.Vehicle;

        int baseline;
        if (context.MaintenanceRecords.Count > 0)
        {
            baseline = context.MaintenanceRecords.Max(m => m.MileageAtService);
        }
        else
        {
            baseline = vehicle.CurrentMileage;
        }

        var nextDueMileage = ((baseline / Interval) + 1) * Interval;
        if (nextDueMileage <= vehicle.CurrentMileage)
        {
            nextDueMileage = ((vehicle.CurrentMileage / Interval) + 1) * Interval;
        }

        yield return new TimelineEvent
        {
            OrganizationId = vehicle.OrganizationId,
            VehicleId = vehicle.Id,
            CustomerId = vehicle.CustomerId,
            Kind = TimelineEventKind.Maintenance,
            Title = $"Révision à {nextDueMileage:N0} km",
            Description = "Cycle d'entretien recommandé tous les 15 000 km.",
            DueAt = null,
            DueMileage = nextDueMileage,
            Status = TimelineEventStatus.Pending,
            Source = TimelineEventSource.AutoGenerated,
            GeneratedFromRule = RuleCode
        };
    }
}
