using CarHorizontal.Domain.Entities.Timeline;

namespace CarHorizontal.Domain.Timeline.Rules;

/// <summary>
/// Generates a recurring maintenance event 6 months after the most recent
/// maintenance (or after the vehicle creation date if none).
/// </summary>
public sealed class SixMonthMaintenanceRule : IRule
{
    public const string RuleCode = "SixMonthMaintenance";
    public string Code => RuleCode;

    public bool Applies(RuleContext context) =>
        context.Vehicle is not null && context.Program is null;

    public IEnumerable<TimelineEvent> Generate(RuleContext context)
    {
        var vehicle = context.Vehicle;

        DateTime baseline;
        if (context.MaintenanceRecords.Count > 0)
        {
            baseline = context.MaintenanceRecords.Max(m => m.PerformedAt);
        }
        else
        {
            baseline = vehicle.PurchasedAt ?? vehicle.CreatedAt;
        }

        var dueAt = DateTime.SpecifyKind(baseline.AddMonths(6), DateTimeKind.Utc);

        if (dueAt < context.Now.AddMonths(-1))
        {
            // catch-up: schedule a maintenance check soon if largely overdue
            dueAt = context.Now.AddDays(14);
        }

        yield return new TimelineEvent
        {
            OrganizationId = vehicle.OrganizationId,
            VehicleId = vehicle.Id,
            CustomerId = vehicle.CustomerId,
            Kind = TimelineEventKind.Maintenance,
            Title = "Entretien semestriel recommandé",
            Description = "Six mois écoulés depuis le dernier passage en atelier.",
            DueAt = dueAt,
            DueMileage = null,
            Status = TimelineEventStatus.Pending,
            Source = TimelineEventSource.AutoGenerated,
            GeneratedFromRule = RuleCode
        };
    }
}
