using CarHorizontal.Domain.Entities.Timeline;
using CarHorizontal.Domain.Entities.Vehicles;

namespace CarHorizontal.Domain.Timeline.Rules;

/// <summary>
/// Seasonal tire swap reminders: winter tires around mid-October,
/// summer tires around mid-April. Skipped for purely electric urban
/// vehicles where the operator may opt out.
/// </summary>
public sealed class TireSwapRule : IRule
{
    public const string RuleCode = "TireSwap";
    public string Code => RuleCode;

    public bool Applies(RuleContext context) => true;

    public IEnumerable<TimelineEvent> Generate(RuleContext context)
    {
        var vehicle = context.Vehicle;
        var now = context.Now;

        var winter = NextOccurrence(now, month: 10, day: 15);
        var summer = NextOccurrence(now, month: 4, day: 15);

        yield return BuildEvent(vehicle, winter, "Pose des pneus hiver");
        yield return BuildEvent(vehicle, summer, "Pose des pneus été");
    }

    private static DateTime NextOccurrence(DateTime now, int month, int day)
    {
        var candidate = new DateTime(now.Year, month, day, 0, 0, 0, DateTimeKind.Utc);
        if (candidate < now.Date)
        {
            candidate = candidate.AddYears(1);
        }
        return candidate;
    }

    private static TimelineEvent BuildEvent(Vehicle vehicle, DateTime dueAt, string title)
    {
        return new TimelineEvent
        {
            OrganizationId = vehicle.OrganizationId,
            VehicleId = vehicle.Id,
            CustomerId = vehicle.CustomerId,
            Kind = TimelineEventKind.TireSwap,
            Title = title,
            Description = "Rappel saisonnier de changement de pneumatiques.",
            DueAt = dueAt,
            DueMileage = null,
            Status = TimelineEventStatus.Pending,
            Source = TimelineEventSource.AutoGenerated,
            GeneratedFromRule = RuleCode
        };
    }
}
