using CarHorizontal.Domain.Entities.Timeline;

namespace CarHorizontal.Domain.Timeline.Rules;

/// <summary>
/// Suggests a trade-in conversation 3 years after the vehicle was purchased.
/// </summary>
public sealed class TradeInOpportunityRule : IRule
{
    public const string RuleCode = "TradeInOpportunity";
    public string Code => RuleCode;

    public bool Applies(RuleContext context) => context.Vehicle.PurchasedAt.HasValue;

    public IEnumerable<TimelineEvent> Generate(RuleContext context)
    {
        var vehicle = context.Vehicle;
        if (!vehicle.PurchasedAt.HasValue) yield break;

        var purchased = DateTime.SpecifyKind(vehicle.PurchasedAt.Value, DateTimeKind.Utc);
        var dueAt = purchased.AddYears(3);

        if (dueAt < context.Now.AddMonths(-6)) yield break;

        yield return new TimelineEvent
        {
            OrganizationId = vehicle.OrganizationId,
            VehicleId = vehicle.Id,
            CustomerId = vehicle.CustomerId,
            Kind = TimelineEventKind.TradeInOpportunity,
            Title = "Opportunité de reprise / renouvellement",
            Description = "Trois ans après l'achat : moment idéal pour proposer une reprise.",
            DueAt = dueAt,
            DueMileage = null,
            Status = TimelineEventStatus.Pending,
            Source = TimelineEventSource.AutoGenerated,
            GeneratedFromRule = RuleCode
        };
    }
}
