using CarHorizontal.Domain.Entities.Timeline;

namespace CarHorizontal.Domain.Timeline.Rules;

/// <summary>
/// Manufacturer warranty typically lasts 2 years from purchase. Generates
/// a single event a few weeks before the expiry.
/// </summary>
public sealed class WarrantyExpiryRule : IRule
{
    public const string RuleCode = "WarrantyExpiry";
    public const int WarrantyYears = 2;
    public string Code => RuleCode;

    public bool Applies(RuleContext context) => context.Vehicle.PurchasedAt.HasValue;

    public IEnumerable<TimelineEvent> Generate(RuleContext context)
    {
        var vehicle = context.Vehicle;
        if (!vehicle.PurchasedAt.HasValue) yield break;

        var purchased = DateTime.SpecifyKind(vehicle.PurchasedAt.Value, DateTimeKind.Utc);
        var expiry = purchased.AddYears(WarrantyYears);

        if (expiry < context.Now.AddMonths(-1)) yield break;

        yield return new TimelineEvent
        {
            OrganizationId = vehicle.OrganizationId,
            VehicleId = vehicle.Id,
            CustomerId = vehicle.CustomerId,
            Kind = TimelineEventKind.WarrantyExpiry,
            Title = "Fin de garantie constructeur",
            Description = "Anticiper avec le client la fin de la garantie pour proposer une extension.",
            DueAt = expiry,
            DueMileage = null,
            Status = TimelineEventStatus.Pending,
            Source = TimelineEventSource.AutoGenerated,
            GeneratedFromRule = RuleCode
        };
    }
}
