import { apiClient } from "@/lib/api/client";
import type { TimelineEventStatusApi } from "@/lib/api/vehicles";

export const timelineEventKinds = [
  "Maintenance",
  "TechnicalInspection",
  "TireSwap",
  "TradeInOpportunity",
  "WarrantyExpiry",
  "Custom",
] as const;
export type TimelineEventKindApi = (typeof timelineEventKinds)[number];

export const timelineEventKindLabels: Record<TimelineEventKindApi, string> = {
  Maintenance: "Entretien",
  TechnicalInspection: "Contrôle technique",
  TireSwap: "Changement de pneus",
  TradeInOpportunity: "Opportunité reprise",
  WarrantyExpiry: "Fin de garantie",
  Custom: "Personnalisé",
};

export const timelineEventStatuses: TimelineEventStatusApi[] = [
  "Pending",
  "Triggered",
  "Done",
  "Skipped",
];

export const timelineEventStatusLabels: Record<TimelineEventStatusApi, string> = {
  Pending: "À faire",
  Triggered: "Déclenché",
  Done: "Fait",
  Skipped: "Ignoré",
};

export interface TimelineEvent {
  id: string;
  vehicleId: string;
  customerId: string;
  vehicleLabel: string;
  licensePlate: string;
  customerFullName: string;
  kind: TimelineEventKindApi;
  title: string;
  description: string | null;
  dueAt: string | null;
  dueMileage: number | null;
  status: TimelineEventStatusApi;
  source: "AutoGenerated" | "Manual";
  generatedFromRule: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface TimelineListResponse {
  items: TimelineEvent[];
  total: number;
  page: number;
  pageSize: number;
}

export interface TimelineListParams {
  vehicleId?: string;
  customerId?: string;
  from?: string;
  to?: string;
  status?: TimelineEventStatusApi;
  kind?: TimelineEventKindApi;
  page?: number;
  pageSize?: number;
  sortDir?: "asc" | "desc";
}

export interface CreateTimelineEventPayload {
  vehicleId: string;
  kind: TimelineEventKindApi;
  title: string;
  description?: string;
  dueAt?: string;
  dueMileage?: number;
}

export interface UpdateTimelineEventPayload {
  title?: string;
  description?: string;
  dueAt?: string;
  dueMileage?: number;
  clearDueAt?: boolean;
  clearDueMileage?: boolean;
  kind?: TimelineEventKindApi;
}

export interface RegenerateTimelineResponse {
  inserted: number;
}

export const timelineApi = {
  async list(
    params: TimelineListParams = {},
    signal?: AbortSignal,
  ): Promise<TimelineListResponse> {
    const { data } = await apiClient.get<TimelineListResponse>("/api/timeline", {
      params,
      signal,
    });
    return data;
  },

  async create(payload: CreateTimelineEventPayload): Promise<TimelineEvent> {
    const { data } = await apiClient.post<TimelineEvent>("/api/timeline", payload);
    return data;
  },

  async update(
    id: string,
    payload: UpdateTimelineEventPayload,
  ): Promise<TimelineEvent> {
    const { data } = await apiClient.patch<TimelineEvent>(
      `/api/timeline/${id}`,
      payload,
    );
    return data;
  },

  async remove(id: string): Promise<void> {
    await apiClient.delete(`/api/timeline/${id}`);
  },

  async complete(id: string): Promise<TimelineEvent> {
    const { data } = await apiClient.post<TimelineEvent>(
      `/api/timeline/${id}/complete`,
    );
    return data;
  },

  async skip(id: string): Promise<TimelineEvent> {
    const { data } = await apiClient.post<TimelineEvent>(
      `/api/timeline/${id}/skip`,
    );
    return data;
  },

  async snooze(id: string, days: number): Promise<TimelineEvent> {
    const { data } = await apiClient.post<TimelineEvent>(
      `/api/timeline/${id}/snooze`,
      { days },
    );
    return data;
  },

  async regenerate(): Promise<RegenerateTimelineResponse> {
    const { data } = await apiClient.post<RegenerateTimelineResponse>(
      "/api/timeline/regenerate",
    );
    return data;
  },
};
