using CarHorizontal.Domain.Common;
using CarHorizontal.Domain.Entities.Catalog;

namespace CarHorizontal.Domain.Entities.Timeline;

public class TimelineEvent : OrganizationEntityBase
{
    public Guid VehicleId { get; set; }
    public Guid CustomerId { get; set; }
    public TimelineEventKind Kind { get; set; }
    public DateTime? DueAt { get; set; }
    public int? DueMileage { get; set; }
    public TimelineEventStatus Status { get; set; } = TimelineEventStatus.Pending;
    public TimelineEventSource Source { get; set; } = TimelineEventSource.AutoGenerated;
    public string? GeneratedFromRule { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? ItemCode { get; set; }
    public MaintenanceItemSeverity? Severity { get; set; }
    public DateTime? EstimatedDueAt { get; set; }
    public int? EstimatedKmRemaining { get; set; }
    public string? MileageConfidenceAtGeneration { get; set; }
}
